### ISSUE TITLE
AttributeError: 'set' object has no attribute 'specials'

### ISSUE THREAD

**Issue by mithro** [enjoy-digital/litex#137]
I'm guessing a bad merge?
```
make: Leaving directory `/home/travis/build/mithro/litex/soc_basesoc_versa_ecp5/software/bios'
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/litex/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/travis/miniconda/envs/litex/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/travis/build/mithro/litex/litex/boards/targets/versa_ecp5.py", line 93, in <module>
    main()
  File "/home/travis/build/mithro/litex/litex/boards/targets/versa_ecp5.py", line 89, in main
    builder.build()
  File "/home/travis/build/mithro/litex/litex/soc/integration/builder.py", line 171, in build
    toolchain_path=toolchain_path, **kwargs)
  File "/home/travis/build/mithro/litex/litex/soc/integration/soc_core.py", line 403, in build
    return self.platform.build(self, *args, **kwargs)
  File "/home/travis/build/mithro/litex/litex/build/lattice/platform.py", line 29, in build
    return self.toolchain.build(self, *args, **kwargs)
  File "/home/travis/build/mithro/litex/litex/build/lattice/trellis.py", line 152, in build
    top_output = platform.get_verilog(fragment, name=build_name, **kwargs)
  File "/home/travis/build/mithro/litex/litex/build/lattice/platform.py", line 26, in get_verilog
    **kwargs)
  File "/home/travis/build/mithro/litex/litex/build/generic_platform.py", line 368, in get_verilog
    create_clock_domains=False, **kwargs)
  File "/home/travis/build/mithro/litex/litex/gen/fhdl/verilog.py", line 380, in convert
    fs, lowered_specials = lower_specials(special_overrides, f.specials)
  File "/home/travis/miniconda/envs/litex/lib/python3.6/site-packages/migen/fhdl/tools.py", line 352, in lower_specials
    fs, lowered_specials_step = _lower_specials_step(overrides, f.specials)
AttributeError: 'set' object has no attribute 'specials'
The command "./.travis-build-socs.sh" exited with 1.
```

**Comment by enjoy-digital** [comment]
I just tested:
- python3 versa_ecp5.py --gateware-toolchain=diamond
- python3 versa_ecp5.py --gateware-toolchain=trellis
and don't reproduce the issue, so i'm closing. If you still have it, can you explain a bit more what you are doing.

**Comment by korimac** [comment]
@mithro  - were you able to resolve this issue? I'm running into the same thing. Thanks!!

**Comment by mithro** [comment]
@korimac It seems to be working fine on LiteX head - See https://travis-ci.org/mithro/litex/builds/514936962

**Comment by mithro** [comment]
@korimac If you can provide more information, maybe it can be debugged...
