### ISSUE TITLE
lxsim error: call to member function 'dump' is ambiguous

### ISSUE THREAD

**Issue by nalzok** [enjoy-digital/litex#712]
I'm on macOS 10.14, and using Python 3.8.2 in an Anaconda virtual environment named `FPGA`. I installed `litex` by:

```
$ cd ~/Developer
$ git clone https://github.com/enjoy-digital/litex.git
$ cd litex
$ conda activate FPGA
$ ./litex_setup.py init install --user
```

I also installed `verilator` with `sudo port install verilator`. The version is

```
$ verilator --version
Verilator 4.034 2020-05-03 rev v4.032-127-g9dc65df98
```

An error occurred when I did `lxsim --cpu-type=vexriscv`. Please check the error log below:

```
$ lxsim --cpu-type=vexriscv
INFO:SoC:        __   _ __      _  __
INFO:SoC:       / /  (_) /____ | |/_/
INFO:SoC:      / /__/ / __/ -_)>  <
INFO:SoC:     /____/_/\__/\__/_/|_|
INFO:SoC:  Build your hardware, easily!
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:Creating SoC... (2020-11-28 17:51:51)
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:FPGA device : SIM.
INFO:SoC:System clock: 1.00MHz.
INFO:SoCBusHandler:Creating Bus Handler...
INFO:SoCBusHandler:32-bit wishbone Bus, 4.0GiB Address Space.
INFO:SoCBusHandler:Adding reserved Bus Regions...
INFO:SoCBusHandler:Bus Handler created.
INFO:SoCCSRHandler:Creating CSR Handler...
INFO:SoCCSRHandler:32-bit CSR Bus, 32-bit Aligned, 16.0KiB Address Space, 2048B Paging, big Ordering (Up to 32 Locations).
INFO:SoCCSRHandler:Adding reserved CSRs...
INFO:SoCCSRHandler:CSR Handler created.
INFO:SoCIRQHandler:Creating IRQ Handler...
INFO:SoCIRQHandler:IRQ Handler (up to 32 Locations).
INFO:SoCIRQHandler:Adding reserved IRQs...
INFO:SoCIRQHandler:IRQ Handler created.
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:Initial SoC:
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:32-bit wishbone Bus, 4.0GiB Address Space.
INFO:SoC:32-bit CSR Bus, 32-bit Aligned, 16.0KiB Address Space, 2048B Paging, big Ordering (Up to 32 Locations).
INFO:SoC:IRQ Handler (up to 32 Locations).
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoCCSRHandler:ctrl CSR allocated at Location 0.
INFO:SoCBusHandler:io0 Region added at Origin: 0x80000000, Size: 0x80000000, Mode: RW, Cached: False Linker: False.
INFO:SoCBusHandler:cpu_bus0 added as Bus Master.
INFO:SoCBusHandler:cpu_bus1 added as Bus Master.
INFO:SoCCSRHandler:cpu CSR allocated at Location 1.
INFO:SoCBusHandler:rom Region added at Origin: 0x00000000, Size: 0x00008000, Mode: R, Cached: True Linker: False.
INFO:SoCBusHandler:rom added as Bus Slave.
INFO:SoC:RAM rom added Origin: 0x00000000, Size: 0x00008000, Mode: R, Cached: True Linker: False.
INFO:SoCBusHandler:sram Region added at Origin: 0x01000000, Size: 0x00002000, Mode: RW, Cached: True Linker: False.
INFO:SoCBusHandler:sram added as Bus Slave.
INFO:SoC:RAM sram added Origin: 0x01000000, Size: 0x00002000, Mode: RW, Cached: True Linker: False.
INFO:SoCBusHandler:main_ram Region added at Origin: 0x40000000, Size: 0x10000000, Mode: RW, Cached: True Linker: False.
INFO:SoCBusHandler:main_ram added as Bus Slave.
INFO:SoC:RAM main_ram added Origin: 0x40000000, Size: 0x10000000, Mode: RW, Cached: True Linker: False.
INFO:SoCCSRHandler:identifier_mem CSR allocated at Location 2.
INFO:SoCCSRHandler:uart_phy CSR allocated at Location 3.
INFO:SoCCSRHandler:uart CSR allocated at Location 4.
INFO:SoCIRQHandler:uart IRQ allocated at Location 0.
INFO:SoCCSRHandler:timer0 CSR allocated at Location 5.
INFO:SoCIRQHandler:timer0 IRQ allocated at Location 1.
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:Finalized SoC:
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:32-bit wishbone Bus, 4.0GiB Address Space.
IO Regions: (1)
io0                 : Origin: 0x80000000, Size: 0x80000000, Mode: RW, Cached: False Linker: False
Bus Regions: (3)
rom                 : Origin: 0x00000000, Size: 0x00008000, Mode: R, Cached: True Linker: False
sram                : Origin: 0x01000000, Size: 0x00002000, Mode: RW, Cached: True Linker: False
main_ram            : Origin: 0x40000000, Size: 0x10000000, Mode: RW, Cached: True Linker: False
Bus Masters: (2)
- cpu_bus0
- cpu_bus1
Bus Slaves: (3)
- rom
- sram
- main_ram
INFO:SoC:32-bit CSR Bus, 32-bit Aligned, 16.0KiB Address Space, 2048B Paging, big Ordering (Up to 32 Locations).
CSR Locations: (6)
- ctrl           : 0
- cpu            : 1
- identifier_mem : 2
- uart_phy       : 3
- uart           : 4
- timer0         : 5
INFO:SoC:IRQ Handler (up to 32 Locations).
IRQ Locations: (2)
- uart   : 0
- timer0 : 1
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoCBusHandler:csr Region added at Origin: 0x82000000, Size: 0x00010000, Mode: RW, Cached: False Linker: False.
INFO:SoCBusHandler:csr added as Bus Slave.
INFO:SoCCSRHandler:bridge added as CSR Master.
INFO:SoCBusHandler:Interconnect: InterconnectShared (2 <-> 4).
make: Nothing to be done for `all'.
 CC       exception.o
 CC       system.o
 CC       id.o
 CC       uart.o
 CC       time.o
 CC       spiflash.o
 CC       i2c.o
 CC       memtest.o
 CC       sim_debug.o
 AR       libbase.a
 AR       libbase-nofloat.a
 CC       sdram.o
 CC       bist.o
 AR       liblitedram.a
 CC       udp.o
 CC       mdio.o
 AR       libliteeth.a
 CC       spiflash.o
 AR       liblitespi.a
make: Nothing to be done for `all'.
 CC       sdcard.o
 CC       spisdcard.o
 AR       liblitesdcard.a
 CC       sata.o
 AR       liblitesata.a
 CC       isr.o
 CC       boot.o
 CC       cmd_bios.o
 CC       cmd_mem.o
 CC       cmd_boot.o
 CC       cmd_i2c.o
 CC       cmd_spiflash.o
 CC       cmd_litedram.o
 CC       cmd_liteeth.o
 CC       cmd_litesdcard.o
 CC       cmd_litesata.o
 CC       main.o
 LD       bios.elf
chmod -x bios.elf
 OBJCOPY  bios.bin
chmod -x bios.bin
python3 -m litex.soc.software.mkmscimg bios.bin --little
python3 -m litex.soc.software.memusage bios.elf /Users/nalzok/build/sim/software/bios/../include/generated/regions.ld riscv64-unknown-elf

ROM usage: 20.79KiB 	(64.95%)
RAM usage: 1.63KiB 	(20.41%)

make: Nothing to be done for `all'.
 CC       exception.o
 CC       system.o
 CC       id.o
 CC       uart.o
 CC       time.o
 CC       spiflash.o
 CC       i2c.o
 CC       memtest.o
 CC       sim_debug.o
 AR       libbase.a
 AR       libbase-nofloat.a
 CC       sdram.o
 CC       bist.o
 AR       liblitedram.a
 CC       udp.o
 CC       mdio.o
 AR       libliteeth.a
 CC       spiflash.o
 AR       liblitespi.a
make: Nothing to be done for `all'.
 CC       sdcard.o
 CC       spisdcard.o
 AR       liblitesdcard.a
 CC       sata.o
 AR       liblitesata.a
 CC       isr.o
 CC       boot.o
 CC       cmd_bios.o
 CC       cmd_mem.o
 CC       cmd_boot.o
 CC       cmd_i2c.o
 CC       cmd_spiflash.o
 CC       cmd_litedram.o
 CC       cmd_liteeth.o
 CC       cmd_litesdcard.o
 CC       cmd_litesata.o
 CC       main.o
 LD       bios.elf
chmod -x bios.elf
 OBJCOPY  bios.bin
chmod -x bios.bin
python3 -m litex.soc.software.mkmscimg bios.bin --little
python3 -m litex.soc.software.memusage bios.elf /Users/nalzok/build/sim/software/bios/../include/generated/regions.ld riscv64-unknown-elf

ROM usage: 20.79KiB 	(64.95%)
RAM usage: 1.63KiB 	(20.41%)

Traceback (most recent call last):
  File "/Users/nalzok/.local/bin/lxsim", line 33, in <module>
    sys.exit(load_entry_point('litex', 'console_scripts', 'lxsim')())
  File "/Users/nalzok/Developer/litex/litex/tools/litex_sim.py", line 421, in main
    vns = builder.build(
  File "/Users/nalzok/Developer/litex/litex/soc/integration/builder.py", line 217, in build
    vns = self.soc.build(build_dir=self.gateware_dir, **kwargs)
  File "/Users/nalzok/Developer/litex/litex/soc/integration/soc.py", line 1054, in build
    return self.platform.build(self, *args, **kwargs)
  File "/Users/nalzok/Developer/litex/litex/build/sim/platform.py", line 54, in build
    return self.toolchain.build(self, *args, **kwargs)
  File "/Users/nalzok/Developer/litex/litex/build/sim/verilator.py", line 235, in build
    _compile_sim(build_name, verbose)
  File "/Users/nalzok/Developer/litex/litex/build/sim/verilator.py", line 154, in _compile_sim
    raise OSError("Subprocess failed with {}\n{}".format(p.returncode, "\n".join(error_messages)))
OSError: Subprocess failed with 2
mkdir -p modules
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C modules -f /Users/nalzok/Developer/litex/litex/build/sim/core/modules/Makefile
mkdir -p xgmii_ethernet
/Applications/Xcode.app/Contents/Developer/usr/bin/make MOD=xgmii_ethernet -C xgmii_ethernet -f /Users/nalzok/Developer/litex/litex/build/sim/core/modules/xgmii_ethernet/Makefile
make[2]: Nothing to be done for `all'.
cp xgmii_ethernet/xgmii_ethernet.so xgmii_ethernet.so
mkdir -p ethernet
/Applications/Xcode.app/Contents/Developer/usr/bin/make MOD=ethernet -C ethernet -f /Users/nalzok/Developer/litex/litex/build/sim/core/modules/ethernet/Makefile
make[2]: Nothing to be done for `all'.
cp ethernet/ethernet.so ethernet.so
mkdir -p serial2console
/Applications/Xcode.app/Contents/Developer/usr/bin/make MOD=serial2console -C serial2console -f /Users/nalzok/Developer/litex/litex/build/sim/core/modules/serial2console/Makefile
make[2]: Nothing to be done for `all'.
cp serial2console/serial2console.so serial2console.so
mkdir -p serial2tcp
/Applications/Xcode.app/Contents/Developer/usr/bin/make MOD=serial2tcp -C serial2tcp -f /Users/nalzok/Developer/litex/litex/build/sim/core/modules/serial2tcp/Makefile
make[2]: Nothing to be done for `all'.
cp serial2tcp/serial2tcp.so serial2tcp.so
mkdir -p clocker
/Applications/Xcode.app/Contents/Developer/usr/bin/make MOD=clocker -C clocker -f /Users/nalzok/Developer/litex/litex/build/sim/core/modules/clocker/Makefile
make[2]: Nothing to be done for `all'.
cp clocker/clocker.so clocker.so
mkdir -p spdeeprom
/Applications/Xcode.app/Contents/Developer/usr/bin/make MOD=spdeeprom -C spdeeprom -f /Users/nalzok/Developer/litex/litex/build/sim/core/modules/spdeeprom/Makefile
make[2]: Nothing to be done for `all'.
cp spdeeprom/spdeeprom.so spdeeprom.so
mkdir -p /Users/nalzok/build/sim/gateware/obj_dir
cc -c -I/usr/local/include/ -o /Users/nalzok/build/sim/gateware/obj_dir/libdylib.o /Users/nalzok/Developer/litex/litex/build/sim/core/libdylib.c
cc -c -I/usr/local/include/ -o /Users/nalzok/build/sim/gateware/obj_dir/modules.o /Users/nalzok/Developer/litex/litex/build/sim/core/modules.c
cc -c -I/usr/local/include/ -o /Users/nalzok/build/sim/gateware/obj_dir/pads.o /Users/nalzok/Developer/litex/litex/build/sim/core/pads.c
cc -c -I/usr/local/include/ -o /Users/nalzok/build/sim/gateware/obj_dir/parse.o /Users/nalzok/Developer/litex/litex/build/sim/core/parse.c
cc -c -I/usr/local/include/ -o /Users/nalzok/build/sim/gateware/obj_dir/sim.o /Users/nalzok/Developer/litex/litex/build/sim/core/sim.c
verilator -Wno-fatal -O3 --cc /Users/nalzok/Developer/pythondata-cpu-vexriscv/pythondata_cpu_vexriscv/verilog/VexRiscv.v --cc /Users/nalzok/build/sim/gateware/sim.v  --top-module sim --exe \
		-DPRINTF_COND=0 \
		sim_init.cpp /Users/nalzok/Developer/litex/litex/build/sim/core/veril.cpp libdylib.o modules.o pads.o parse.o sim.o \
		--top-module sim \
		 \
		-CFLAGS "-I/usr/local/include/ -I/Users/nalzok/Developer/litex/litex/build/sim/core" \
		-LDFLAGS "-L/usr/local/lib -lpthread -ljson-c -lm -lstdc++ -ldl -levent" \
		--trace \
		 \
		 \
		--unroll-count 256 \
		--output-split 5000 \
		--output-split-cfuncs 500 \
		--output-split-ctrace 500 \
		 \
		-Wno-BLKANDNBLK \
		-Wno-WIDTH
%Warning-CASEINCOMPLETE: /Users/nalzok/build/sim/gateware/sim.v:1075:3: Case values incompletely covered (example pattern 0x3)
                                                                      : ... In instance sim
 1075 |   case (csr_bankarray_interface0_bank_bus_adr[1:0])
      |   ^~~~
                         ... Use "/* verilator lint_off CASEINCOMPLETE */" and lint_on around source to disable this message.
make -j -C /Users/nalzok/build/sim/gateware/obj_dir -f Vsim.mk Vsim
/usr/bin/clang++  -I.  -MMD -I/opt/local/share/verilator/include -I/opt/local/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -faligned-new -fbracket-depth=4096 -fcf-protection=none -Qunused-arguments -Wno-parentheses-equality -Wno-sign-compare -Wno-uninitialized -Wno-unused-parameter -Wno-unused-variable -Wno-shadow     -I/usr/local/include/ -I/Users/nalzok/Developer/litex/litex/build/sim/core   -c -o veril.o /Users/nalzok/Developer/litex/litex/build/sim/core/veril.cpp
/usr/bin/clang++  -I.  -MMD -I/opt/local/share/verilator/include -I/opt/local/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -faligned-new -fbracket-depth=4096 -fcf-protection=none -Qunused-arguments -Wno-parentheses-equality -Wno-sign-compare -Wno-uninitialized -Wno-unused-parameter -Wno-unused-variable -Wno-shadow     -I/usr/local/include/ -I/Users/nalzok/Developer/litex/litex/build/sim/core   -c -o sim_init.o ../sim_init.cpp
/usr/bin/clang++  -I.  -MMD -I/opt/local/share/verilator/include -I/opt/local/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -faligned-new -fbracket-depth=4096 -fcf-protection=none -Qunused-arguments -Wno-parentheses-equality -Wno-sign-compare -Wno-uninitialized -Wno-unused-parameter -Wno-unused-variable -Wno-shadow     -I/usr/local/include/ -I/Users/nalzok/Developer/litex/litex/build/sim/core   -c -o verilated.o /opt/local/share/verilator/include/verilated.cpp
/usr/bin/clang++  -I.  -MMD -I/opt/local/share/verilator/include -I/opt/local/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -faligned-new -fbracket-depth=4096 -fcf-protection=none -Qunused-arguments -Wno-parentheses-equality -Wno-sign-compare -Wno-uninitialized -Wno-unused-parameter -Wno-unused-variable -Wno-shadow     -I/usr/local/include/ -I/Users/nalzok/Developer/litex/litex/build/sim/core   -c -o verilated_dpi.o /opt/local/share/verilator/include/verilated_dpi.cpp
/usr/bin/clang++  -I.  -MMD -I/opt/local/share/verilator/include -I/opt/local/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -faligned-new -fbracket-depth=4096 -fcf-protection=none -Qunused-arguments -Wno-parentheses-equality -Wno-sign-compare -Wno-uninitialized -Wno-unused-parameter -Wno-unused-variable -Wno-shadow     -I/usr/local/include/ -I/Users/nalzok/Developer/litex/litex/build/sim/core   -c -o verilated_vcd_c.o /opt/local/share/verilator/include/verilated_vcd_c.cpp
/usr/bin/clang++  -I.  -MMD -I/opt/local/share/verilator/include -I/opt/local/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -faligned-new -fbracket-depth=4096 -fcf-protection=none -Qunused-arguments -Wno-parentheses-equality -Wno-sign-compare -Wno-uninitialized -Wno-unused-parameter -Wno-unused-variable -Wno-shadow     -I/usr/local/include/ -I/Users/nalzok/Developer/litex/litex/build/sim/core   -c -o Vsim.o Vsim.cpp
/usr/bin/clang++  -I.  -MMD -I/opt/local/share/verilator/include -I/opt/local/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -faligned-new -fbracket-depth=4096 -fcf-protection=none -Qunused-arguments -Wno-parentheses-equality -Wno-sign-compare -Wno-uninitialized -Wno-unused-parameter -Wno-unused-variable -Wno-shadow     -I/usr/local/include/ -I/Users/nalzok/Developer/litex/litex/build/sim/core   -c -o Vsim_sim.o Vsim_sim.cpp
/usr/bin/clang++  -I.  -MMD -I/opt/local/share/verilator/include -I/opt/local/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -faligned-new -fbracket-depth=4096 -fcf-protection=none -Qunused-arguments -Wno-parentheses-equality -Wno-sign-compare -Wno-uninitialized -Wno-unused-parameter -Wno-unused-variable -Wno-shadow     -I/usr/local/include/ -I/Users/nalzok/Developer/litex/litex/build/sim/core   -c -o Vsim_VexRiscv.o Vsim_VexRiscv.cpp
/usr/bin/clang++  -I.  -MMD -I/opt/local/share/verilator/include -I/opt/local/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -faligned-new -fbracket-depth=4096 -fcf-protection=none -Qunused-arguments -Wno-parentheses-equality -Wno-sign-compare -Wno-uninitialized -Wno-unused-parameter -Wno-unused-variable -Wno-shadow     -I/usr/local/include/ -I/Users/nalzok/Developer/litex/litex/build/sim/core   -c -o Vsim_VexRiscv__1.o Vsim_VexRiscv__1.cpp
/usr/bin/clang++  -I.  -MMD -I/opt/local/share/verilator/include -I/opt/local/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -faligned-new -fbracket-depth=4096 -fcf-protection=none -Qunused-arguments -Wno-parentheses-equality -Wno-sign-compare -Wno-uninitialized -Wno-unused-parameter -Wno-unused-variable -Wno-shadow     -I/usr/local/include/ -I/Users/nalzok/Developer/litex/litex/build/sim/core   -c -o Vsim_VexRiscv__2.o Vsim_VexRiscv__2.cpp
/usr/bin/clang++  -I.  -MMD -I/opt/local/share/verilator/include -I/opt/local/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -faligned-new -fbracket-depth=4096 -fcf-protection=none -Qunused-arguments -Wno-parentheses-equality -Wno-sign-compare -Wno-uninitialized -Wno-unused-parameter -Wno-unused-variable -Wno-shadow     -I/usr/local/include/ -I/Users/nalzok/Developer/litex/litex/build/sim/core   -c -o Vsim__Slow.o Vsim__Slow.cpp
/usr/bin/clang++  -I.  -MMD -I/opt/local/share/verilator/include -I/opt/local/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -faligned-new -fbracket-depth=4096 -fcf-protection=none -Qunused-arguments -Wno-parentheses-equality -Wno-sign-compare -Wno-uninitialized -Wno-unused-parameter -Wno-unused-variable -Wno-shadow     -I/usr/local/include/ -I/Users/nalzok/Developer/litex/litex/build/sim/core   -c -o Vsim_sim__Slow.o Vsim_sim__Slow.cpp
/usr/bin/clang++  -I.  -MMD -I/opt/local/share/verilator/include -I/opt/local/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -faligned-new -fbracket-depth=4096 -fcf-protection=none -Qunused-arguments -Wno-parentheses-equality -Wno-sign-compare -Wno-uninitialized -Wno-unused-parameter -Wno-unused-variable -Wno-shadow     -I/usr/local/include/ -I/Users/nalzok/Developer/litex/litex/build/sim/core   -c -o Vsim_VexRiscv__Slow.o Vsim_VexRiscv__Slow.cpp
/usr/bin/clang++  -I.  -MMD -I/opt/local/share/verilator/include -I/opt/local/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -faligned-new -fbracket-depth=4096 -fcf-protection=none -Qunused-arguments -Wno-parentheses-equality -Wno-sign-compare -Wno-uninitialized -Wno-unused-parameter -Wno-unused-variable -Wno-shadow     -I/usr/local/include/ -I/Users/nalzok/Developer/litex/litex/build/sim/core   -c -o Vsim_VexRiscv__1__Slow.o Vsim_VexRiscv__1__Slow.cpp
/usr/bin/clang++  -I.  -MMD -I/opt/local/share/verilator/include -I/opt/local/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -faligned-new -fbracket-depth=4096 -fcf-protection=none -Qunused-arguments -Wno-parentheses-equality -Wno-sign-compare -Wno-uninitialized -Wno-unused-parameter -Wno-unused-variable -Wno-shadow     -I/usr/local/include/ -I/Users/nalzok/Developer/litex/litex/build/sim/core   -c -o Vsim__Dpi.o Vsim__Dpi.cpp
/usr/bin/clang++  -I.  -MMD -I/opt/local/share/verilator/include -I/opt/local/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -faligned-new -fbracket-depth=4096 -fcf-protection=none -Qunused-arguments -Wno-parentheses-equality -Wno-sign-compare -Wno-uninitialized -Wno-unused-parameter -Wno-unused-variable -Wno-shadow     -I/usr/local/include/ -I/Users/nalzok/Developer/litex/litex/build/sim/core   -c -o Vsim__Trace.o Vsim__Trace.cpp
/usr/bin/clang++  -I.  -MMD -I/opt/local/share/verilator/include -I/opt/local/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -faligned-new -fbracket-depth=4096 -fcf-protection=none -Qunused-arguments -Wno-parentheses-equality -Wno-sign-compare -Wno-uninitialized -Wno-unused-parameter -Wno-unused-variable -Wno-shadow     -I/usr/local/include/ -I/Users/nalzok/Developer/litex/litex/build/sim/core   -c -o Vsim__Syms.o Vsim__Syms.cpp
/usr/bin/clang++  -I.  -MMD -I/opt/local/share/verilator/include -I/opt/local/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -faligned-new -fbracket-depth=4096 -fcf-protection=none -Qunused-arguments -Wno-parentheses-equality -Wno-sign-compare -Wno-uninitialized -Wno-unused-parameter -Wno-unused-variable -Wno-shadow     -I/usr/local/include/ -I/Users/nalzok/Developer/litex/litex/build/sim/core   -c -o Vsim__Trace__Slow.o Vsim__Trace__Slow.cpp
/Users/nalzok/Developer/litex/litex/build/sim/core/veril.cpp:75:10: error: call to member function 'dump' is ambiguous
    tfp->dump(main_time);
    ~~~~~^~~~
/opt/local/share/verilator/include/verilated_vcd_c.h:391:10: note: candidate function
    void dump(vluint64_t timeui) { m_sptrace.dump(timeui); }
         ^
/opt/local/share/verilator/include/verilated_vcd_c.h:394:10: note: candidate function
    void dump(double timestamp) { dump(static_cast<vluint64_t>(timestamp)); }
         ^
/opt/local/share/verilator/include/verilated_vcd_c.h:395:10: note: candidate function
    void dump(vluint32_t timestamp) { dump(static_cast<vluint64_t>(timestamp)); }
         ^
/opt/local/share/verilator/include/verilated_vcd_c.h:396:10: note: candidate function
    void dump(int timestamp) { dump(static_cast<vluint64_t>(timestamp)); }
         ^
1 error generated.
make[1]: *** [veril.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [sim] Error 2
```

**Comment by enjoy-digital** [comment]
@nalzok: The issue seems specific to the environment or Verilator version (works fine with Ubuntu 18.04 + Verilator 4.013 + GCC). Are you able to test the compilation with GCC instead of Clang?

**Comment by nalzok** [comment]
> Are you able to test the compilation with GCC instead of Clang?

I would love to try that out, but how do I specify the toolchain? Using `CC=gcc CXX=g++ lxsim --cpu-type=vexriscv` does not seem to work, i.e. the script still invokes `clang++` and produces the same error as above.

**Comment by nickoe** [comment]
I get the exact same problem with `Verilator 4.108 2021-01-10 rev v4.106-158-g484b76e5b` on a macos image, and I just updated with brew. I guess there is a more fundemental issue somehow? Header files?

**Comment by nickoe** [comment]
This appears to be caused by this commit, I guess. https://github.com/enjoy-digital/litex/commit/38054874ac1dc80f75faca9b9af590a4754b9fff

In that commit the argument to dump was an `unsigned int ticks` but it is now using `uint64_t main_time`. So I just tried to cast main_time to an unsigned int and it could build just fine.

```
diff --git a/litex/build/sim/core/veril.cpp b/litex/build/sim/core/veril.cpp
index ee435d37..6357bc0a 100644
--- a/litex/build/sim/core/veril.cpp
+++ b/litex/build/sim/core/veril.cpp
@@ -72,7 +72,7 @@ extern "C" void litex_sim_tracer_dump()
   }
 
   if (dump_enabled && tfp_start <= main_time && main_time <= tfp_end) {
-    tfp->dump(main_time);
+    tfp->dump((unsigned int)main_time);
   }
 }
```

I would certainly not claim I understand this code, but that was just an observation I made. I guess this is not a proper fix, hence I just pasted it here for whoever want to pursue this issue further.

**Comment by enjoy-digital** [comment]
Thanks @nickoe for looking at this, casting to `vluint64_t` will probably be more appropriate. Can you try with: https://github.com/enjoy-digital/litex/commit/d3407c67b189d2c338766febb3bf2c57f6f80d1d? @nalzok: Can you also give it a try?

**Comment by nalzok** [comment]
I can confirm that the latest commit works now. Kudos to everybody involved!
